version: "3.3"
services:
    Coderhousemongodb:
       image: mongo:latest
       container_name: Coderhousemongodb
       restart: always
       ports:
           - "27017:27017"
       volumes:
           - data:/data/db

    backend:
      build:
        dockerfile: Dockerfile.dev
        context: ./backend/
      container_name: backend
      restart: always
      ports:
        - "5000:5000"
      env_file:
        - ./backend/.env
      volumes:
        - ./backend:/backend
        - /backend/node_modules
      depends_on:
        - Coderhousemongodb 
    frontend:
      build:
        dockerfile: Dockerfile.dev
        context: ./
      container_name: codershousefrontend
      ports:
        - "80:80"
        - "443:443"
      env_file:
        - ./codershousefrontend/.env
      volumes:
        - ./deploy/default.conf:/etc/nginx/sites-available/default
        - /var/certs/etc-letsencrypt:/etc/letsencrypt
      depends_on:
        - backend   
volumes:
   data:              


